FROM golang

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY . .
# RUN go mod download && go mod verify

RUN go build dispatcher.go

CMD ["./dispatcher"]