version: "3"
services:
  words:
    build: ./DockerFile_words
    restart: always
    container_name: words
    ports:
      # These ports are in format <host-port>:<container-port>
      - '8080:8080' # Public HTTP Port
    environment:
      # 
    volumes:
      - /var/lib/docker/volumes/words:/data/words
    networks:
      - test
  db:
    build: ./DockerFile_db
    restart: unless-stopped
    container_name: db_container
    environment:
      ENV POSTGRES_PASSWORD "docker"
      ENV POSTGRES_DB "world"
    volumes:
      - /var/lib/docker/volumes/postgress:/var/lib/postgress
    networks:
      - test
    depends_on:
      - words

  web:
    build: ./DockerFile_web
    restart: always
    ports:
      - '80:80' # Public HTTP Port
    volumes:
      - /var/lib/docker/volumes/web:/www/web
    networks:
      - test

networks:
  test:
    driver: bridge
